kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "sample-pipeline"
spec:
  source:
    git:
      uri: "https://github.com/Ashinerer/websocket"
  strategy:
    type: "Docker"
    dockerStrategy:
      dockerfilePath:
  output:
    to:
      kind: "DockerImage"
      name: ":websocket:latest"