kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "sample-pipeline"
spec:
  source:
    git:
      uri: "https://github.com/Ashinerer/websocket"
  strategy:
    type: "Source"
    sourceStrategy:
      from:
        kind: "ImageStreamTag"
        name: "openjdk:8"
  output:
    to:
      kind: "ImageStreamTag"
      name: "webskt:latest"